services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./html:/var/www/html
      - ./caddy_data:/data
      - ./caddy_config:/config

networks:
  web:
    external: true