services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "securerootpassword"
      MARIADB_USER: "kiwi"
      MARIADB_PASSWORD: "kiwi@123"
      MARIADB_DATABASE: "maria"
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb: