services:
  mc:
    image: itzg/minecraft-server:java17-alpine
    container_name: minecraft
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    networks:
      - docker-network
    environment:
      MEMORY: "2G"
      EULA: "TRUE"
      TYPE: "PURPUR"
      USE_AIKAR_FLAGS: true
      ENABLE_ROLLING_LOGS: true
      USE_SIMD_FLAGS: true
      ONLINE_MODE: FALSE
    volumes:
      - ./mc-data:/data
networks:
  docker-network:
    name: docker-network
    external: true