services:
  mc:
    image: itzg/minecraft-server:java17-alpine
    container_name: minecraft
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      MEMORY: "2G"
      EULA: "TRUE"
      TYPE: "PUFFERFISH"
      VERSION: "1.20.4"
      USE_AIKAR_FLAGS: true
      ENABLE_ROLLING_LOGS: true
      USE_SIMD_FLAGS: true
      ONLINE_MODE: FALSE
      MODRINTH_PROJECTS: viaversion,viarewind,viabackwards
      SPIGET_RESOURCES: 34315,28140,57242 # LuckPerms, Vault, Spark
    volumes:
      - ./mc-data:/data